query=PREFIX js: <http://jena.apache.org/ARQ/jsFunction#>

SELECT (js:linreg_xtx(GROUP_CONCAT(STR(?x)), GROUP_CONCAT(?y)) AS ?xtx)
       (js:linreg_xty(GROUP_CONCAT(STR(?x)), GROUP_CONCAT(?y)) AS ?xty)

{

  ?patient <fairvasc:x> ?x.

  ?patient <fairvasc:y> ?y.

}
